prompts:
  welcome: "Welcome to Rock, Paper, Scissors, Lizard, Spock!"
  name: "Enter your name:"
  greeting: "Hi, "
  valid_name: "Make sure to use a valid name.\n
              "

  choice: "Choose your weapon:\n
            \r1. Rock     (r)\n
            \r2. Paper    (p)\n
            \r3. Scissors (ss)\n
            \r4. Lizard   (l)\n
            \r5. Spock    (sp)\n"
  choice_example: "For example: Enter '1', 'r' or 'rock' to select 'Rock'."
  valid_choice: "Hmm...that doesn't look like a valid choice.\n
                "

  win_message:
  - "You won!"
  lose_message:
  - "Computer won!"
  tie_message:
  - "It's a tie!"

choices:
  rock:
    inputs: ['1', '1.', 'r', 'rock']
    beat: ['lizard', 'scissors']
  paper:
    inputs: ['2', '2.', 'p', 'paper']
    beat: ['rock', 'spock']
  scissors:
    inputs: ['3', '3.', 'ss', 'scissors']
    beat: ['paper', 'lizard']
  lizard:
    inputs: ['4', '4.', 'l', 'lizard']
    beat: ['spock', 'paper']
  spock:
    inputs: ['5', '5.', 'sp', 'spock']
    beat: ['scissors', 'rock']
