prompts:
  welcome: "Welcome to 'Rock, Paper, Scissors, Lizard, Spock'!"
  greeting: "Hi, "
  name: "Enter your name:"
  valid_name: "Make sure to use a valid name.\n
              "

  view_rules: "Would you like to learn the rules of the game?"
  view_rules_example: "Enter 'Y' to view the rules, or 'N' to proceed to the game."
  valid_view_rules: "Please enter 'Y' to view the rules, or 'N' to proceed to the game."
  rules_1: |
    -------------------------------------------------------------------
                                   RULES
    -------------------------------------------------------------------
    Objectives:
    - Select a play (Rock, Paper, Scissors, Lizard, or Spock) that 
      defeats the computer's play
    - First player to 3 wins is the grand winner!

    [Page 1/2]
    -------------------------------------------------------------------
    => Press 'n' to view the next page.
    => Press any other key to start the game.
    -------------------------------------------------------------------
  rules_2: |
    -------------------------------------------------------------------
                                   RULES
    -------------------------------------------------------------------
    Win Conditions:
    - [Scissors] cuts [Paper]
    - [Paper] covers [Rock]
    - [Rock] crushes [Lizard]
    - [Lizard] poisons [Spock]
    - [Spock] smashes [Scissors]
    - [Scissors] decapitates [Lizard]
    - [Lizard] eats [Paper]
    - [Paper] disproves [Spock]
    - [Spock] vaporizes [Rock]
    - [Rock] crushes [Scissors]

    [Page 2/2]
    -------------------------------------------------------------------
    => Press 'b' to view the previous page.
    => Press any other key to start the game.
    -------------------------------------------------------------------

  choice: |
    Choose your weapon:
    (e.g. Enter '1', 'r' or 'rock' to select 'Rock'.)

    1. Rock     (r)
    2. Paper    (p)
    3. Scissors (sc)
    4. Lizard   (l)
    5. Spock    (sp)
  valid_choice: |
    Hmm...that doesn't look like a valid choice.

    For example: Enter '1', 'r' or 'rock' to select 'Rock'.
  break: "-------------------------------------------------------------------"
  current_score: "                          Current Score"
  round_label: "Round "
  winner:
    win: "You won!"
    lose: "Computer won!"
    tie: "It's a tie!"
  computer_label: "Computer: "
  win_message:
  - "Yowch!"
  - "You'll be sorry!"
  - "What rotten luck."
  - "What the-Oof!"
  - "Oh, deary me."
  - "Just you wait..."
  - "I'm just being lazy."
  - "You'll regret that!"
  - "Quit picking on me!"
  - "At times, I really hate this game..."
  lose_message:
  - "Take that!"
  - "Victory is mine!"
  - "You don't stand a chance!"
  - "That was easy!"
  - "Whoo! Success!"
  - "Gotcha!"
  - "You had it coming!"
  - "Revenge! ...is sweet."
  - "Nehehehehaha."
  - "Now that's what I call a perfect move!"
  tie_message:
  - "Bummer..."
  - "Yawns..."
  - "Boring..."
  - "Guess that's it."
  - "That's a coincidence!"
  - "C'mon...We got places to go..."
  - "Get a move on!"
  - "Oh c'mon!"
  - "I survived!"
  - "This is taking too long!"
  continue: "Press any key to continue."

  match:
    win:
      text: "Hooray! You beat the computer and are the grand winner!"
      art: |
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡀⠀⠀
        ⠀⣠⣴⣾⣿⣿⡇⠀⠀⠀⠀⠀⢀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⡿⠀⠀⠀
        ⣰⣿⣿⣿⠿⣿⡇⠀⠀⠀⣰⣷⣿⣿⠀⠀⠀⠀⣠⣢⣾⣷⠀⠀⣿⠃⣀⠀⠀
        ⣿⣿⠋⠀⠀⠀⠁⠀⠀⠀⢻⣿⢹⡏⠀⢀⡀⠸⣿⢻⣿⠿⣦⢀⣿⣾⣿⣶⠆
        ⣿⣯⠀⠀⠀⠀⢀⣶⣿⣶⣼⣿⢸⡇⢰⣿⣿⣼⣿⠈⣁⣤⣿⢻⡏⢹⡟⠀⠀
        ⢻⣿⣷⣤⣤⣴⣿⣿⠀⢿⣿⡿⢸⣿⣿⡃⣿⣇⣿⢸⠋⣹⣿⣼⡧⣄⣻⣄⠀
        ⠀⠙⠛⠛⠛⠋⣿⣿⣄⣼⣿⠓⠀⠻⣿⣷⣿⠼⠿⠟⠿⠛⠹⢿⣇⢻⣦⣿⠂
        ⠀⠀⠀⠀⠀⠀⠘⠿⣿⠿⠃⣠⣦⠀⠈⠉⣿⠀⠀⠀⠀⠀⠀⢸⣿⣦⣉⠁⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣆⠀⢠⡇⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⠃⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⠿⠿⠟⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⡿⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠃⠀⠀
    lose:
      text: "Oh no, you lost the match! Better luck next time."
      art: |
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⠀⠀⠀⣶⡆⠀⣰⣿⠇⣾⡿⠛⠉⠁
        ⠀⣠⣴⠾⠿⠿⠀⢀⣾⣿⣆⣀⣸⣿⣷⣾⣿⡿⢸⣿⠟⢓⠀⠀
        ⣴⡟⠁⣀⣠⣤⠀⣼⣿⠾⣿⣻⣿⠃⠙⢫⣿⠃⣿⡿⠟⠛⠁⠀
        ⢿⣝⣻⣿⡿⠋⠾⠟⠁⠀⠹⠟⠛⠀⠀⠈⠉⠀⠉⠀⠀⠀⠀⠀
        ⠀⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⣀⢀⣠⣤⣴⣤⣄⠀
        ⠀⠀⠀⠀⣀⣤⣤⢶⣤⠀⠀⢀⣴⢃⣿⠟⠋⢹⣿⣣⣴⡿⠋⠀
        ⠀⠀⣰⣾⠟⠉⣿⡜⣿⡆⣴⡿⠁⣼⡿⠛⢃⣾⡿⠋⢻⣇⠀⠀
        ⠀⠐⣿⡁⢀⣠⣿⡇⢹⣿⡿⠁⢠⣿⠷⠟⠻⠟⠀⠀⠈⠛⠀⠀
        ⠀⠀⠙⠻⠿⠟⠋⠀⠀⠙⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
  # match_win: |
  #   Hooray! You beat the computer and are the grand winner!
  # match_lose: |
  #   You lost the match... Better luck next time.

  again: "Want to have a rematch?"
  again_example: "Enter 'Y' to continue, or 'N' to end the game."
  valid_again: "Please enter 'Y' to continue, or 'N' to end the game."
  bye: "Thank you for playing 'Rock, Paper, Scissors, Lizard, Spock'! Goodbye!"

choices:
  rock:
    inputs: ['1', '1.', 'r', 'rock']
    beat: ['lizard', 'scissors']
  paper:
    inputs: ['2', '2.', 'p', 'paper']
    beat: ['rock', 'spock']
  scissors:
    inputs: ['3', '3.', 'sc', 'scissors']
    beat: ['paper', 'lizard']
  lizard:
    inputs: ['4', '4.', 'l', 'lizard']
    beat: ['spock', 'paper']
  spock:
    inputs: ['5', '5.', 'sp', 'spock']
    beat: ['scissors', 'rock']
