prompts:
  welcome: "Welcome to 'Rock, Paper, Scissors, Lizard, Spock'!"
  name: "Enter your name:"
  valid_name: "Make sure to use a valid name.\n
              "

  view_rules: "Would you like to learn the rules of the game?"
  view_rules_example: "Enter 'Y' to view the rules, or 'N' to proceed to the game."
  valid_view_rules: "Please enter 'Y' to view the rules, or 'N' to proceed to the game."
  rules: |
    -------------------------------------------------------------------
                                   RULES
    -------------------------------------------------------------------
    Objectives:
    - Select a play (R, P, SC, L, SP) that defeats the computer's play
    - First player to 3 wins is the winner of the round

    Win Conditions:
    - [Scissors] cuts [Paper]
    - [Paper] covers [Rock]
    - [Rock] crushes [Lizard]
    - [Lizard] poisons [Spock]
    - [Spock] smashes [Scissors]
    - [Scissors] decapitates [Lizard]
    - [Lizard] eats [Paper]
    - [Paper] disproves [Spock]
    - [Spock] vaporizes [Rock]
    - [Rock] crushes [Scissors]
    -------------------------------------------------------------------
                      Press any key to start the game
    -------------------------------------------------------------------
  again: "Want to have a rematch?"
  again_example: "Enter 'Y' to continue, or 'N' to end the game."
  valid_again: "Please enter 'Y' to continue, or 'N' to end the game."
  bye: "Thank you for playing 'Rock, Paper, Scissors, Lizard, Spock'! Goodbye!"

  choice: |
    Choose your weapon:
    1. Rock     (r)
    2. Paper    (p)
    3. Scissors (sc)
    4. Lizard   (l)
    5. Spock    (sp)
  choice_example: "For example: Enter '1', 'r' or 'rock' to select 'Rock'."
  valid_choice: "Hmm...that doesn't look like a valid choice.\n
                "
  break: "-------------------------------------------------------------------"
  current_score: "                          Current Score"

  win_message:
  - "You won!"
  lose_message:
  - "Computer won!"
  tie_message:
  - "It's a tie!"

choices:
  rock:
    inputs: ['1', '1.', 'r', 'rock']
    beat: ['lizard', 'scissors']
  paper:
    inputs: ['2', '2.', 'p', 'paper']
    beat: ['rock', 'spock']
  scissors:
    inputs: ['3', '3.', 'sc', 'scissors']
    beat: ['paper', 'lizard']
  lizard:
    inputs: ['4', '4.', 'l', 'lizard']
    beat: ['spock', 'paper']
  spock:
    inputs: ['5', '5.', 'sp', 'spock']
    beat: ['scissors', 'rock']
