#! /usr/bin/env ruby

require "pg"

def list_expenses
  db = PG.connect(dbname: "expenses")
  result = db.exec "SELECT * FROM expenses ORDER BY created_on ASC"
  result.each do |tuple|
    columns = [
      tuple["id"].rjust(3),
      tuple["created_on"].rjust(10),
      tuple["amount"].rjust(12),
      tuple["memo"]
    ]

    puts columns.join(" | ")
  end
end

def display_help
  text = <<~HELP
  An expense recording system

  Commands:

  add AMOUNT MEMO - record a new expense
  clear - delete all expenses
  list - list all expenses
  delete NUMBER - remove expense with id NUMBER
  search QUERY - list expenses with a matching memo field
  HELP

  puts text
end

case ARGV.first
when "list"
  list_expenses
else
  display_help
end
