markers:
  initial: ' '
  player: 'X'
  computer: 'O'

players: ['player', 'computer']

winning_lines: [[0, 1, 2], [3, 4, 5], [6, 7, 8], # horizontal
                [0, 3, 6], [1, 4, 7], [2, 5, 8], # vertical
                [0, 4, 8], [2, 4, 6]]            # diagonal

board: |+
  
  -------------------
  |     |     |     |
  |  %s  |  %s  |  %s  |
  |     |     |     |
  ------+-----+-----+
  |     |     |     |
  |  %s  |  %s  |  %s  |
  |     |     |     |
  ------+-----+-----+
  |     |     |     |
  |  %s  |  %s  |  %s  |
  |     |     |     |
  -------------------

prompts:
  welcome: ">> Welcome to Tic-Tac-Toe!\n"
  view_rules: ">> Would you like to learn the rules of the game?\n>> Enter 'Y' to view the rules, or 'N' to proceed to the game."
  invalid_view_rules: ">> Please enter 'Y' to view the rules, or 'N' to proceed to the game."
  rules: |
    -------------------------------------------------------------------
                                   RULES
    -------------------------------------------------------------------
    Objectives:
    - You (as 'X') and the computer (as 'O') take turns putting marks
      on empty squares in a 3 x 3 square grid.
    - The first player to get 3 marks in a row (vertical, horizontal,
      or diagonal) wins the round.
    - First player to 5 wins is the grand winner!

    Possible positions to mark:
    
             |       |
        [1]  |  [2]  |  [3]
             |       |
      -------+-------+-------
             |       |
        [4]  |  [5]  |  [6]
             |       |
      -------+-------+-------
             |       |
        [7]  |  [8]  |  [9]
             |       |

    -------------------------------------------------------------------
     >> Press any other key to start the game.
    -------------------------------------------------------------------
    
  choose_square: ">> Choose a square (%s):"
  invalid_square: ">> Sorry, that's not a valid choice."

  winner_player: ">> You won!"
  winner_computer: "Computer won!"
  tie: ">> It's a tie!"

  again: ">> Want to have a rematch?\n>> Enter 'Y' to continue, or 'N' to end the game."
  invalid_again: ">> Please enter 'Y' to continue, or 'N' to end the game."
  bye: ">> Thank you for playing Tic-Tac-Toe! Goodbye!"
