board: |+
  
  -------------------------
  |       |       |       |
  |   %s   |   %s   |   %s   |                Squares
  |       |       |       |             -------------
  --------+-------+--------             | 1 | 2 | 3 |
  |       |       |       |             |---+---+---|
  |   %s   |   %s   |   %s   |             | 4 | 5 | 6 |
  |       |       |       |             |---+---+---| 
  --------+-------+--------             | 7 | 8 | 9 |
  |       |       |       |             -------------
  |   %s   |   %s   |   %s   |
  |       |       |       |
  -------------------------
