board: |+
  
  -------------------------           Possible positions
  |       |       |       |             -------------
  |   %s   |   %s   |   %s   |             | 1 | 2 | 3 |
  |       |       |       |             |---+---+---|
  --------+-------+--------             | 4 | 5 | 6 |
  |       |       |       |             |---+---+---| 
  |   %s   |   %s   |   %s   |             | 7 | 8 | 9 |
  |       |       |       |             -------------
  --------+-------+--------
  |       |       |       |
  |   %s   |   %s   |   %s   |
  |       |       |       |
  -------------------------
