en: 
  welcome: "Welcome to Mortgage Calculator!"
  break: "\r--------------------------------------------------------------------------"

  total_loan: "What is your total loan amount?"
  loan_example: "For example, enter '10000', '10 000' or '$10,000'."
  valid_loan: "Please enter a positive number.\n
              "

  apr: "What is your estimated Annual Percentage Rate (APR) in % ?"
  apr_example: "For example, enter '5' or '5%'."
  valid_apr: "Please enter a number between '0' and '100'.\n
              "

  month_or_year: "Would you like to enter your loan duration in months or years?\n
                  \ \ 1. Months\n
                  \ \ 2. Years"
  valid_duration: "Please enter '1' for 'months' or '2' for 'years'.\n
                  "
  month: "What is the duration of your loan in months?"
  month_example: "For example, enter '10' for 10 months."
  valid_month: "Please enter a number between '1' and '600'.\n
                "

  year: "What is the duration of your loan in years?"
  year_example: "For example, enter '10' for 10 years."
  valid_year: "Please enter a number between '1' and '50'.\n
              "

  input_summary: "Based on your input:\n
                  "
  loan_input: "Total Loan Amount: "
  apr_input: "APR: "
  duration_input: "Loan Duration: "

  calculate: "Calculating your results..."
  results: "Results:\n
            "
  monthly_payment: "Estimated Monthly Payment: "
  monthly_interest: "Monthly Interest Rate: "
  duration: "Duration of your Loan: "

  total_interest: "Total Interest: "
  total_payment: "Total Payment: "

  again: "Do you want to perform another calculation?"
  again_example: "Enter 'Y' to calculate again, or 'N' to exit."
  valid_again: "Please enter 'Y' to calculate again, or 'N' to exit."
  bye: "Thank you for using Mortgage Calculator. Goodbye!"
