en: 
  welcome: "Welcome to Mortgage Calculator! Enter your name: "
  greeting: "Hi, "
  valid_name: "Make sure to use a valid name."

  total_loan: "What is your total loan amount? Example: $10,000"
  valid_loan: "Hmm... that doesn't look like a valid loan amount."

  apr: "What is your estimated Annual Percentage Rate (APR)? Example: 5%"
  valid_apr: "Hmm... that doesn't look like a valid APR."

  month_or_year: "Would you like to enter your loan duration in months or years?"
  valid_duration: "Hmm... that doesn't look like a valid duration."
