en: 
  welcome: "Welcome to Mortgage Calculator!\n
            \r-------------------------------------------"

  total_loan: "What is your total loan amount?"
  loan_example: "For example, enter '10000', '10 000' or '$10,000'."
  valid_loan: "Hmm... that doesn't look like a valid loan amount."

  apr: "What is your estimated Annual Percentage Rate (APR) in %?"
  apr_example: "For example, enter '5' or '5%'."
  valid_apr: "Hmm... that doesn't look like a valid APR."

  month_or_year: "Would you like to enter your loan duration in months or years?\n
                  \ \ 1. Months\n
                  \ \ 2. Years"
  valid_duration: "Hmm... that doesn't look like a valid duration."
  month: "What is the duration of your loan in months?"
  month_example: "For example, enter '10' for 10 months."
  year: "What is the duration of your loan in years?"
  year_example: "For example, enter '10' for 10 years."


  calculate: "Calculating..."
  results: "-------------------------------------------\n
            \rResults:\n
            "
  monthly_payment: "Your estimated monthly payment: "  
  monthly_interest: "Your monthly interest rate: "
  duration: "Duration of your loan: "

  total_payment: "Total loan payment: "
  total_interest: "Total interest: "

  again: "Do you want to perform another calculation? (Y to calculate again, N to exit)"
  valid_again: 'Please enter Y to calculate again, or N to exit.'
  bye: "Thank you for using Mortgage Calculator. Goodbye!"
