en: 
  welcome: "Welcome to Calculator! Enter your name: "
  greeting: "Hi, "
  valid_name: "Make sure to use a valid name."

  first_num: "What's the first number?"
  second_num: "What's the second number?"
  valid_num: "Hmm... that doesn't look like a valid number."

  operator_prompt: "What operation would you like to perform?\n
                    1) add\n
                    2) subtract\n
                    3) multiply\n
                    4) divide\n"
  valid_operator: "Must choose 1, 2, 3, or 4."
  add: "Adding the two numbers..."
  subtract: "Subtracting the two numbers..."
  multiply: "Multiplying the two numbers..."
  divide: "Dividing the two numbers..."

  result: "The result is "

  again: "Do you want to perform another calculation? (Y to calculate again, N to exit)"
  valid_again: 'Please enter Y to calculate again, or N to exit.'
  bye: "Thank you for using the calculator. Goodbye!"

# Translations can be improved
cn:
  welcome: "欢迎来到计算器! 请输入你的名字: "
  greeting: "嗨, "
  valid_name: "请使用有效的名称。"

  first_num: "第一个数字是什么？"
  second_num: "第二个数字是什么？"
  valid_num: "嗯...这看起来不像是个有效的数字"

  operator_prompt: "你想使用什么算术？\n
                    1) 加法\n
                    2) 减法\n
                    3) 乘法\n
                    4) 除法\n"
  valid_operator: "必须选择1、2、3 或 4。"
  add: "将两个数字相加..."
  subtract: "将两个数字相减..."
  multiply: "将两个数字相乘..."
  divide: "将两个数字相除..."

  result: "答案是 "

  again: "你想再进行另一种计算方法吗？ (Y 表示再次计算, N 表示退出)"
  valid_again: '请输入 Y 以再次计算 或 输入 N 以退出。'
  bye: "谢谢你使用计算器。再见!"

ja:
  welcome: "電卓へようこそ! 名前を入力してください。"
  greeting: "こんにちは, "
  valid_name: "有効な名前を使用してください。"

  first_num: "1つ目の数字は?"
  second_num: "2つ目の数字は?"
  valid_num: "うーん...有効な数字に見えないんだけど。"

  operator_prompt: "どのような計算を行いたいですか？\n
                    1) 足し算\n
                    2) 引き算\n
                    3) 掛け算\n
                    4) 割り算\n"
  valid_operator: "1、2、3、4のいずれかを選択しなければならない。"
  add: "2つの数字を足すと..."
  subtract: "2つの数字を引き算すると..."
  multiply: "2つの数字を掛け合わせると..."
  divide: "2つの数字を割ると..."

  result: "結果は "

  again: "もう1度計算を行いますか? (Yで再計算、Nで終了)"
  valid_again: '再度計算する場合はYを、終了する場合はNを入力してください。'
  bye: "電卓をご利用いただきありがとうございました。さようならー"
