
welcome: "Welcome to Calculator! Enter your name: "
valid_name: "Make sure to use a valid name."

first_num: "What's the first number?"
second_num: "What's the second number?"
valid_num: "Hmm... that doesn't look like a valid number."

operator_prompt: "What operation would you like to perform?\n
                  1) add\n
                  2) subtract\n
                  3) multiply\n
                  4) divide\n"
valid_operator: "Must choose 1, 2, 3, or 4."
add: "Adding"
subtract: "Subtracting"
multiply: "Multiplying"
divide: "Dividing"
operator_message: " the two numbers.."

result: "The result is "

again: "Do you want to perform another calculation? (Y to calculate again)"
bye: "Thank you for using the calculator. Goodbye!"

