choices:
  rock:
    inputs: ['r', 'rock']
    beats: ['lizard', 'scissors']
  paper:
    inputs: ['p', 'paper']
    beats: ['rock', 'spock']
  scissors:
    inputs: ['sc', 'scissors']
    beats: ['paper', 'lizard']
  lizard:
    inputs: ['l', 'lizard']
    beats: ['spock', 'paper']
  spock:
    inputs: ['sp', 'spock']
    beats: ['scissors', 'rock']

greetings:
  SpongeBob: "SpongeBob: \"Hi, how are ya?\""
  Patrick: "Patrick: \"Hey Patrick! D-oh, I'm Patrick.\""
  Squidward: "Squidward: \"Is it time for you to already ruin my day?\""

win:
  SpongeBob: "SpongeBob: \"If you believe in yourself and with a tiny pinch of magic, all your dreams can come true.\""
  Patrick: "Patrick: \"Here comes a giant fist!\""
  Squidward: "Squidward: \"I'm a winner, see my prize! You're a loser who sits and cries.\""

lose:
  SpongeBob: "SpongeBob: \"Hey, if I close my eyes it doesn't seem so dark.\""
  Patrick: "Patrick: \"Are you the bad guy?\""
  Squidward: "Squidward: \"Well, it wouldn't be the first time you ruined everything.\""

tie:
  SpongeBob: "SpongeBob: \"Gary, I'm absorbing these blows like I'm made of some sort of spongy material.\""
  Patrick: "Patrick: \"Do it again; I wasn't looking!\""
  Squidward: "Squidward: \"Too bad that didn't kill me.\""

rules: |
    -------------------------------------------------------------------
                                   RULES
    -------------------------------------------------------------------
    Objectives:
    - Select a play (Rock, Paper, Scissors, Lizard, or Spock) that 
      defeats your opponents's play.
    - First player to 3 wins is the grand winner!

    Win Conditions:
    - [Rock]     beats [Scissors] and [Lizard]
    - [Paper]    beats [Rock]     and [Spock]
    - [Scissors] beats [Paper]    and [Lizard]
    - [Lizard]   beats [Paper]    and [Spock]
    - [Spock]    beats [Scissors] and [Rock]
    -------------------------------------------------------------------
    Press [enter] to start the game.
    ------------------------------------------------------------------
