suits: ["\u2664", "\u2665", "\u2667", "\u2666"]
cards : { '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10, 'Jack': 10, 'Queen': 10, 'King': 10, 'Ace': [1, 11] }

ace_totals: { 1: [1, 11], 2: [2, 12, 22], 3: [3, 13, 23, 33], 4: [4, 14, 24, 34, 44] }

hidden_hands: |
  =================================================================
  Dealer has %s and ?%s
  You have: %s, for a total of %d
  =================================================================
visible_hands: |
  =================================================================
  Dealer has: %s, for a total of %s
  You have: %s, for a total of %d
  =================================================================

prompts:
  hit_stay: "=> (H)it or (S)tay?"
  invalid_hit_stay: "=> Hm...that doesn't look like a valid choice.\n=> Enter 'h' or 'hit' to hit, and 's' and 'stay' to stay."
