markers:
  initial: ' '
  player: 'X'
  computer: 'O'

players: ['player', 'computer']

winning_lines: [[0, 1, 2], [3, 4, 5], [6, 7, 8], # horizontal
                [0, 3, 6], [1, 4, 7], [2, 5, 8], # vertical
                [0, 4, 8], [2, 4, 6]]            # diagonal

scoreboard: |
  --------------------------               
          CURRENT SCORE                    
                                           
  Your Wins - %d                            
  Computer's Wins - %d                         
  Ties - %d                                 
  --------------------------               
board: |+
  
  -------------------------           Possible positions
  |       |       |       |             -------------
  |   %s   |   %s   |   %s   |             | 1 | 2 | 3 |
  |       |       |       |             |---+---+---|
  --------+-------+--------             | 4 | 5 | 6 |
  |       |       |       |             |---+---+---| 
  |   %s   |   %s   |   %s   |             | 7 | 8 | 9 |
  |       |       |       |             -------------
  --------+-------+--------
  |       |       |       |
  |   %s   |   %s   |   %s   |
  |       |       |       |
  -------------------------

prompts:
  welcome: "=> Welcome to Tic-Tac-Toe!"
  view_rules: "=> Would you like to learn the rules of the game?\n=> Enter 'Y' to view the rules, or 'N' to proceed to the game."
  invalid_view_rules: "=> Please enter 'Y' to view the rules, or 'N' to proceed to the game."
  rules: |
    -------------------------------------------------------------------
                                   RULES
    -------------------------------------------------------------------

    Objectives:

    - You (as 'X') and the computer (as 'O') take turns putting marks
      on empty squares in a 3 x 3 square grid.
    - The first player to get 3 marks in a row (vertical, horizontal,
      or diagonal) wins the round.
    - First player to 5 wins is the winner of the match!

    Possible positions to mark:
    
      -------------------------
      |       |       |       |
      |  [1]  |  [2]  |  [3]  |
      |       |       |       |
      --------+-------+--------
      |       |       |       |
      |  [4]  |  [5]  |  [6]  |
      |       |       |       |
      --------+-------+--------
      |       |       |       |
      |  [7]  |  [8]  |  [9]  |
      |       |       |       |
      -------------------------

    -------------------------------------------------------------------
     => Press any other key to start the game.
    -------------------------------------------------------------------

  start_game: |
    => Alright, you will be playing against the computer.
    => The goal is to get 3 marks in a row.
    => First one to win 5 rounds is the winner of the match!

    => Loading game...

  pick_player: "=> You get to pick the starting player."
  pick_computer: "=> Computer gets to pick the starting player."

  player_choice: "=> Enter '1' to go first or '2' for the computer to go first."
  invalid_player_choice: "=> Please enter '1' to go first or '2' for the computer to go first."

  first_player: "=> You go first."
  first_computer: "=> Computer goes first."

  choose_square: "=> Choose a square (%s):"
  invalid_square: "=> Sorry, that's not a valid choice."

  round_player: "=> You won!\n "
  round_computer: "Computer won!\n "
  tie: "=> It's a tie!\n "
  continue: "=> Want to continue?\n=> Enter 'Y' to continue, or 'N' to end the game."
  invalid_continue: "=> Please enter 'Y' to continue, or 'N' to end the game."

  champion_player: "=> Hooray! You beat the computer and are the grand winner!"
  champion_computer: "=> Oh no, you lost the match! Better luck next time."
  play_again: "=> Want to have a rematch?\n=> Enter 'Y' to continue, or 'N' to end the game."
  invalid_play_again: "=> Please enter 'Y' to continue, or 'N' to end the game."
  bye: "=> Thank you for playing Tic-Tac-Toe! Goodbye!"
